% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Chapter 5 - Foundations for Inference},
  pdfauthor={Kenan Sooklall},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{geometry}
\usepackage{multicol}
\usepackage{multirow}

\title{Chapter 5 - Foundations for Inference}
\author{Kenan Sooklall}
\date{}

\begin{document}
\maketitle

\textbf{Heights of adults.} (7.7, p.~260) Researchers studying
anthropometry collected body girth measurements and skeletal diameter
measurements, as well as age, weight, height and gender, for 507
physically active individuals. The histogram below shows the sample
distribution of heights in centimeters.

\includegraphics{KSooklall_Homework5_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{tabular}{r | l}
min & 147.2 \\
Q1 & 163.8 \\
median & 170.3
mean    & 171.1 \\
sd  & 9.4 \\
Q3 & 177.8 \\
max & 198.1 
\end{tabular}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  What is the point estimate for the average height of active
  individuals? What about the median?
\end{enumerate}

point estimate = 171.1

median = 170.3

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  What is the point estimate for the standard deviation of the heights
  of active individuals? What about the IQR?
\end{enumerate}

Standard deviation = 9.4

IQR = (Q3 - Q1) = (177.8 - 163.8) = 14

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Is a person who is 1m 80cm (180 cm) tall considered unusually tall?
  And is a person who is 1m 55cm (155cm) considered unusually short?
  Explain your reasoning.
\end{enumerate}

180 cm is taller than the average person likewise 155 cm is shorter than
the average. If the definition of unusual is greater than one standard
deviation then both of these individuals are unusually tall/short.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  The researchers take another random sample of physically active
  individuals. Would you expect the mean and the standard deviation of
  this new sample to be the ones given above? Explain your reasoning.
\end{enumerate}

I expected the mean and standard deviation to be close to the one we
already have.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  The sample means obtained are point estimates for the mean height of
  all active individuals, if the sample of individuals is equivalent to
  a simple random sample. What measure do we use to quantify the
  variability of such an estimate (Hint: recall that
  \(SD_x = \frac{\sigma}{\sqrt{n}}\))? Compute this quantity using the
  data from the original sample under the condition that the data are a
  simple random sample.
\end{enumerate}

Use the standard error

\begin{Shaded}
\begin{Highlighting}[]
\FloatTok{9.4} \OperatorTok{/}\StringTok{ }\KeywordTok{sqrt}\NormalTok{(}\DecValTok{507}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4174687
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\clearpage

\textbf{Thanksgiving spending, Part I.} The 2009 holiday retail season,
which kicked off on November 27, 2009 (the day after Thanksgiving), had
been marked by somewhat lower self-reported consumer spending than was
seen during the comparable period in 2008. To get an estimate of
consumer spending, 436 randomly sampled American adults were surveyed.
Daily consumer spending for the six-day period after Thanksgiving,
spanning the Black Friday weekend and Cyber Monday, averaged \$84.71. A
95\% confidence interval based on this sample is (\$80.31, \$89.11).
Determine whether the following statements are true or false, and
explain your reasoning.

\includegraphics{KSooklall_Homework5_files/figure-latex/unnamed-chunk-3-1.pdf}

\(\mu=84.71 \\\) 95\% confidence (80.31, 89.11)

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  We are 95\% confident that the average spending of these 436 American
  adults is between \$80.31 and \$89.11.
\end{enumerate}

False, the range is a population parameter so we are 100\% sure the
average spending of these 436 American adults is between \$80.31 and
\$89.11.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  This confidence interval is not valid since the distribution of
  spending in the sample is right skewed.
\end{enumerate}

Since n=436 which is \textgreater{} 30 we know by the Central limit
theorem the distribution will be normal, this sample is right skewed.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  95\% of random samples have a sample mean between \$80.31 and \$89.11.
\end{enumerate}

False, based on the information provided here we can't tell. However if
the actual mean is 84.71 then we can say that 95\% of random samples
with have a mean between \$80.31 and \$89.11.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  We are 95\% confident that the average spending of all American adults
  is between \$80.31 and \$89.11.
\end{enumerate}

True for this sample of 436.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  A 90\% confidence interval would be narrower than the 95\% confidence
  interval since we don't need to be as sure about our estimate.
\end{enumerate}

True, A lower confidence interval is narrower

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
  In order to decrease the margin of error of a 95\% confidence interval
  to a third of what it is now, we would need to use a sample 3 times
  larger.
\end{enumerate}

False, No you would need to sample 9 times more since margin of error is
calculated by sqrt(p ( (1-p) / n)), the square root causes the
non-linear requirement

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{6}
\tightlist
\item
  The margin of error is 4.4. True, p = (89.11+80.31)/2=84.71 which is 1
  margin of error from the upper and lower bound
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\clearpage

\textbf{Gifted children, Part I.} Researchers investigating
characteristics of gifted children col- lected data from schools in a
large city on a random sample of thirty-six children who were identified
as gifted children soon after they reached the age of four. The
following histogram shows the dis- tribution of the ages (in months) at
which these children first counted to 10 successfully. Also provided are
some sample statistics.

\includegraphics{KSooklall_Homework5_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{tabular}{r | l}
n   & 36 \\
min & 21 \\
mean    & 30.69 \\
sd  & 4.31 \\
max & 39 
k & 48
\end{tabular}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  Are conditions for inference satisfied? The requirement for inference
  is n\textgreater30 and 36 just meets the requirement
\item
  Suppose you read online that children first count to 10 successfully
  when they are 32 months old, on average. Perform a hypothesis test to
  evaluate if these data provide convincing evidence that the average
  age at which gifted children fist count to 10 successfully is less
  than the general average of 32 months. Use a significance level of
  0.10.
\end{enumerate}

\(H_o: \mu = 32 \\\) \(H_a: \mu < 32 \\\)

For significance level 0.1 -\textgreater{} z = 1.645

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{std =}\StringTok{ }\FloatTok{4.31}
\NormalTok{n =}\StringTok{ }\DecValTok{36}
\NormalTok{df =}\StringTok{ }\NormalTok{n }\OperatorTok{-}\StringTok{ }\DecValTok{1}
\NormalTok{X_bar =}\StringTok{ }\DecValTok{32}
\NormalTok{mu =}\StringTok{ }\FloatTok{30.69}
\NormalTok{se <-}\StringTok{ }\NormalTok{std }\OperatorTok{/}\StringTok{ }\KeywordTok{sqrt}\NormalTok{(n)}
\NormalTok{t <-}\StringTok{ }\NormalTok{(X_bar }\OperatorTok{-}\StringTok{ }\NormalTok{mu) }\OperatorTok{/}\StringTok{ }\NormalTok{se}
\NormalTok{t_crit <-}\StringTok{ }\FloatTok{1.69}
\end{Highlighting}
\end{Shaded}

Since t (1.823) \textgreater{} t\_crit(1.69) we reject the null
hypothesis

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Interpret the p-value in context of the hypothesis test and the data.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p_val <-}\StringTok{ }\DecValTok{1} \OperatorTok{-}\StringTok{ }\KeywordTok{pnorm}\NormalTok{(t, }\DataTypeTok{mean=}\DecValTok{0}\NormalTok{, }\DataTypeTok{sd=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The p\_val is 0.034 so there is a 3.4\% chance that the difference
between those two are due to chance

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Calculate a 90\% confidence interval for the average age at which
  gifted children first count to 10 successfully.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{c}\NormalTok{(}\FloatTok{30.69} \OperatorTok{-}\StringTok{ }\NormalTok{t_crit }\OperatorTok{*}\StringTok{ }\NormalTok{se, }\FloatTok{30.69} \OperatorTok{+}\StringTok{ }\NormalTok{t_crit }\OperatorTok{*}\StringTok{ }\NormalTok{se)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 29.47602 31.90398
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  Do your results from the hypothesis test and the confidence interval
  agree? Explain.
\end{enumerate}

The confidence interval of 10\% produced a range of 29.5 - 31.9 months
at which a child who counts to 10 can be considered gifted. The
hypothesis test of 32 is outside the range so it was correct to reject
it.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\clearpage

\textbf{Gifted children, Part II.} Exercise above describes a study on
gifted children. In this study, along with variables on the children,
the researchers also collected data on the mother's and father's IQ of
the 36 randomly sampled gifted children. The histogram below shows the
distribution of mother's IQ. Also provided are some sample statistics.

\includegraphics{KSooklall_Homework5_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{tabular}{r | l}
n   & 36 \\
min & 101 \\
mean    & 118.2 \\
sd  & 6.5 \\
max & 131 
\end{tabular}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Perform a hypothesis test to evaluate if the data provide convincing
  evidence that the average IQ of mothers of gifted children is
  different than the average IQ for the population at large, which is
  100. Use a significance level of 0.10.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{se =}\StringTok{ }\FloatTok{6.5} \OperatorTok{/}\StringTok{ }\KeywordTok{sqrt}\NormalTok{(}\DecValTok{36}\NormalTok{)}
\NormalTok{mu =}\StringTok{ }\FloatTok{118.2}
\NormalTok{t =}\StringTok{ }\NormalTok{(mu }\OperatorTok{-}\StringTok{ }\DecValTok{100}\NormalTok{) }\OperatorTok{/}\StringTok{ }\NormalTok{se}
\end{Highlighting}
\end{Shaded}

It looks like t=16.8 \textgreater\textgreater{} t\_crit=1.69 therefore
we fail to reject the null hypothesis

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Calculate a 90\% confidence interval for the average IQ of mothers of
  gifted children.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{c}\NormalTok{(mu }\OperatorTok{-}\StringTok{ }\NormalTok{t_crit }\OperatorTok{*}\StringTok{ }\NormalTok{se, mu }\OperatorTok{+}\StringTok{ }\NormalTok{t_crit }\OperatorTok{*}\StringTok{ }\NormalTok{se)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 116.3692 120.0308
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Do your results from the hypothesis test and the confidence interval
  agree? Explain.
\end{enumerate}

The confidence interval of 10\% produced an IQ range of 116-119 for
mothers of gifted children. The hypothesis test of 100 is outside the
range so it was correct to fail to reject it.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\clearpage

\textbf{CLT.} Define the term ``sampling distribution'' of the mean, and
describe how the shape, center, and spread of the sampling distribution
of the mean change as sample size increases.

As sample size (n) increases the shape of the curve becomes more narrow
and skewness less apparent. The shape is more normal and the center p is
a closer approximation of the true population mean.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\clearpage

\textbf{CFLBs.} A manufacturer of compact fluorescent light bulbs
advertises that the distribution of the lifespans of these light bulbs
is nearly normal with a mean of 9,000 hours and a standard deviation of
1,000 hours.

\$ H\_o: \mu = 9000, \sigma=1000\$ \$ H\_a: \$

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  What is the probability that a randomly chosen light bulb lasts more
  than 10,500 hours?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X =}\StringTok{ }\DecValTok{10500}
\NormalTok{mu =}\StringTok{ }\DecValTok{9000}
\NormalTok{std =}\StringTok{ }\DecValTok{1000}
\NormalTok{z =}\StringTok{ }\NormalTok{(X }\OperatorTok{-}\StringTok{ }\NormalTok{mu) }\OperatorTok{/}\StringTok{ }\NormalTok{std}
\DecValTok{1} \OperatorTok{-}\StringTok{ }\KeywordTok{pnorm}\NormalTok{(z)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0668072
\end{verbatim}

There is a 6.7\% chance that a a randomly chosen light bulb lasts more
than 10,500 hours

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Describe the distribution of the mean lifespan of 15 light bulbs.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n =}\StringTok{ }\DecValTok{15}
\NormalTok{se =}\StringTok{ }\NormalTok{std}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n)}
\end{Highlighting}
\end{Shaded}

The problem statement states the distribution is nearly normal; however
since n\textless30 the standard error will be large, here it's 258.2

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  What is the probability that the mean lifespan of 15 randomly chosen
  light bulbs is more than 10,500 hours?
\end{enumerate}

\(P(X > \mu | n=15) = 1 - P(X <= \mu | n=15)\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n =}\StringTok{ }\DecValTok{15}
\NormalTok{X_bar =}\StringTok{ }\DecValTok{10500}
\DecValTok{1} \OperatorTok{-}\StringTok{ }\KeywordTok{pnorm}\NormalTok{(X_bar, }\DataTypeTok{mean=}\NormalTok{mu, }\DataTypeTok{sd =}\NormalTok{ se)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.133452e-09
\end{verbatim}

It looks like there is a near 0 chance that 15 randomly chosen light
bulbs will last more than 10,500 hours.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Sketch the two distributions (population and sampling) on the same
  scale.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{population =}\StringTok{ }\DecValTok{100000}
\NormalTok{mu =}\StringTok{ }\DecValTok{9000}
\NormalTok{std =}\StringTok{ }\DecValTok{1000}
\NormalTok{n =}\StringTok{ }\DecValTok{15}
\NormalTok{dist =}\StringTok{ }\KeywordTok{rnorm}\NormalTok{(population, mu, std)}
\NormalTok{sample_pop15 =}\StringTok{ }\KeywordTok{sample}\NormalTok{(dist, }\DataTypeTok{size=}\NormalTok{n)}

\NormalTok{data <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{x=}\NormalTok{dist, }\DataTypeTok{label=}\KeywordTok{c}\NormalTok{(}\StringTok{'Population'}\NormalTok{)), }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{x=}\NormalTok{sample_pop15,             }\DataTypeTok{label=}\KeywordTok{c}\NormalTok{(}\StringTok{'Sampling'}\NormalTok{)))}

\NormalTok{data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{x,}\DataTypeTok{color=}\NormalTok{label)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{KSooklall_Homework5_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  Could you estimate the probabilities from parts (a) and (c) if the
  lifespans of light bulbs had a skewed distribution?
\end{enumerate}

I believe we can always ``estimate'' the probabilities; however, the
accuracy of those estimates will be low with a skewed distribution
especially since n is so small (\textless30)

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\clearpage

\textbf{Same observation, different sample size.} Suppose you conduct a
hypothesis test based on a sample where the sample size is n = 50, and
arrive at a p-value of 0.08. You then refer back to your notes and
discover that you made a careless mistake, the sample size should have
been n = 500. Will your p-value increase, decrease, or stay the same?
Explain.

n=50 p\_val=0.08

Noting that our initial n \textgreater{} 30 and our true n
\textgreater\textgreater{} 30 ie 500, I would first expect the stand
error to go down since due to it's sensitivity to n.~A lower standard
error will give us results closer to the true population parameters and
thus lowering our p\_value.

\end{document}
