---
title: "Homework 6 - DATA 607"
author: "Kenan Sooklall"
date: "3/18/2021"
output: html_document
---
                Assignment – Working with XML and JSON in R

Pick three of your favorite books on one of your favorite subjects. At least one of the books should have more than one author. For each book, include the title, authors, and two or three other attributes that you find interesting.

Topic Computer Science
```{r}
books = c('Hello World', 'The signal and the noise', 'Why we sleep')
authors = c('Hannah Fry', 'Nate Silver', 'Matthew Walker')
attributes1 = c('green cover', 'yellow cover', 'black cover')
attributes2 = c(2018, 2012, 2017)
```

Take the information that you’ve selected about these three books, and separately create three files which
store the book’s information in HTML (using an html table), XML, and JSON formats (e.g. “books.html”,
“books.xml”, and “books.json”). To help you better understand the different file structures, I’d prefer that you
create each of these files “by hand” unless you’re already very comfortable with the file formats.
Write R code, using your packages of choice, to load the information from each of the three sources into
separate R data frames. Are the three data frames identical?
Your deliverable is the three source files and the R code. If you can, package your assignment solution up into
an .Rmd file and publish to rpubs.com. [This will also require finding a way to make your three text files
accessible from the web].