---
title: "eigenshoes"
author: "Minator"
date: "2/19/2021"
output: html_document


```{r}
library(EBImage)
library(OpenImageR)
library(jpeg)
library(ggplot)

path <- "/home/kenan/Documents/learning/masters/CUNY-SPS-Masters-DS/DATA_605/homeworks/homework4/images/"
n=17
files=list.files(path, pattern="*.jpg")[1:n]
height=1200
width=2500
scale=20
```


```{r}
plot_jpeg = function(path, add=FALSE)
{ jpg = readJPEG(path, native=T) # read the file
  res = dim(jpg)[2:1] # get the resolution, [x, y]
  if (!add) # initialize an empty plot area if add==FALSE
    plot(1,1,xlim=c(1,res[1]),ylim=c(1,res[2]),asp=1,type='n',xaxs='i',yaxs='i',xaxt='n',yaxt='n',xlab='',ylab='',bty='n')
  rasterImage(jpg,1,1,res[1],res[2])
}
```


```{r}
im=array(rep(0,length(files)*height/scale*width/scale*3), dim=c(length(files), height/scale, width/scale,3))

for (i in 1:n){
  temp=resize(readJPEG(paste0(path, files[i])),height/scale, width/scale)
  im[i,,,]=array(temp,dim=c(1, height/scale, width/scale,3))}
```


```{r}
flat=matrix(0, n, prod(dim(im)[2:4]))
for (i in 1:n) {
  newim <- readJPEG(paste0(path, files[i]))
  r=as.vector(im[i,,,1]); g=as.vector(im[i,,,2]);b=as.vector(im[i,,,3])
  flat[i,] <- t(c(r, g, b))
}
shoes=as.data.frame(t(flat))
```

KEN
```{r}
img <- im[1,,,]
org <- t(flat)
#imageShow(array((org[,1]), c(60,125,3)))

sdata<-scale(org)
means<-attr(sdata, "scaled:center")
std<-attr(sdata, "scaled:scale")

# Check
# bb<-sdata * std + means
# all(round(bb[1,]) == org[1,])

scov<-cov(sdata)
seign<-eigen(scov)

lambda <- seign$values
vect <- seign$vectors

# Reconstruct
aa <- std * (vect %*% t(sdata) * lambda) + means
imageShow(array(aa[,1], c(60,125,3)))
```

```{r}
par(mfrow=c(3,3))
par(mai=c(.3,.3,.3,.3))
for (i in 1:n){  #plot the first images only
plot_jpeg(writeJPEG(im[i,,,]))
}
```


```{r}
scaled=scale(shoes, center = TRUE, scale = TRUE)
mean.shoe=attr(scaled, "scaled:center") #saving for classification
std.shoe=attr(scaled, "scaled:scale")  #saving for classification...later
Sigma_=cov(scaled)
```

The eigen values tells you how much variance your capturing

```{r}
myeigen=eigen(Sigma_)
lamda <- myeigen$values
vect <- myeigen$vectors
cumsum(myeigen$values) / sum(myeigen$values)
```


```{r}
scaling=diag(myeigen$values[1:5]^(-1/2)) / (sqrt(nrow(scaled)-1))
eigenshoes=scaled%*%myeigen$vectors[,1:5]%*%scaling
imageShow(array(eigenshoes[,1], c(60,125,3)))
```


```{r}
height=1200
width=2500
scale=20
newdata=im
dim(newdata)=c(length(files),height*width*3/scale^2)
mypca=princomp(t(as.matrix(newdata)), scores=TRUE, cor=TRUE)
```


```{r}
mypca2=t(mypca$scores)
dim(mypca2)=c(length(files),height/scale,width/scale,3)
par(mfrow=c(5,5))
par(mai=c(.001,.001,.001,.001))
for (i in 1:n){#plot the first 25 Eigenshoes only
plot_jpeg(writeJPEG(mypca2[i,,,], bg="white"))  #complete without reduction
}
```


```{r}
a=round(mypca$sdev[1:n]^2/ sum(mypca$sdev^2),3)
cumsum(a)
```


```{r}
x = t(t(eigenshoes)%*%scaled)
```